### ISSUE TITLE
Add `py.typed` maker?

### ISSUE THREAD

**Issue by mccalluc** [jrialland/python-astar#12]
I'm using this astar successfully in my code, but when I try to check typing with mypy I get this error:
```
error: Skipping analyzing "astar": module is installed, but missing library stubs or py.typed marker  [import]
note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```
... so for now I'm ignoring this line:
```python
from astar import AStar  # type: ignore
```

I think the fix may just be to add an empty `astar/py.typed` file, but I'm fairly new to python typing, so there may be more to it than just that.

(Looking at [ci configuration](https://github.com/jrialland/python-astar/blob/master/.github/workflows/pythonpackage.yml), I'm not sure your type definitions are being checked now. I haven't run mypy on this package.)

**Comment by jrialland** [comment]
Thank you for pointing that out ! To be fair type hints are quite new for me too. I'm going to add the file, and re-release.
