### ISSUE TITLE
"pop index out of range" error since version 0.96

### ISSUE THREAD

**Issue by vhamon** [jrialland/python-astar#15]
Hello,

I have the following error when using python astar since 0.96 while it is working with version 0.95 and below :

    File "/usr/local/lib/python3.11/site-packages/astar/__init__.py", line 57, in pop
        item = self.sortedlist.pop(0)

     File "/usr/local/lib/python3.11/site-packages/sortedcontainers/sortedlist.py", line 1343, in pop
         raise IndexError('pop index out of range')

I use the following code : 

    def neighbors(neighbor):
        for node, distance in nodes[neighbor]:
            yield node

    def distance(node_1, node_2):
        for node, distance in nodes[node_1]:
            if node == node_2:
                return distance

    def cost(node, goal):
        return 1

    best_path = astar.find_path(start_node_name, goal_node_name,
                                neighbors_fnct=neighbors,
                                heuristic_cost_estimate_fnct=cost, distance_between_fnct=distance)`

What is special in my case is that I have an incomplete set of nodes.
Start node : A
Goal node : D
I.e. I have the following nodes : 
 {'A': [('B', 200000)],
  'C': [('D', 200000)],
  'D': [('E', 200000)],
  'E': [('F', 200000)],
  'B': [],
  'F': []}
As you can see, I have no path to go from B to C.
I expect in this case that _astar.find_path()_ returns None (meaning no path found).
This was okay before 0.95 but it's not anymore.
From what I saw, it happens since the refactoring to use sortedcontainers : https://github.com/jrialland/python-astar/commit/71bd3c7841b4dc0f607b9583a1594343cf51210d

Do you have any suggestion/solution for that except using version 0.95 to not use sortedcontainers (which is now defined as a mandatory requirement by your module) ?

Thanks in advance,
Valentin

**Comment by jrialland** [comment]
Hi,

thanks for reporting the issue.

I think it should not happen and that it might be a problem with the new implementation, I'm definitely going to have a look at it !

**Comment by jrialland** [comment]
the OpenSet class missed the method that allows to check if it is empty, as it was the case at the time is used a simple list and heappop(). Fix is https://github.com/jrialland/python-astar/commit/1da7fb5c1ec607a518c66a4fdcb6c136df407d5d

Released version 0.99 with the fix

**Comment by vhamon** [comment]
Hello Julien,

I tested and it works well now !

Thanks a lot,
Bye.
