### ISSUE TITLE
heuristic_cost_estimate affects results

### ISSUE THREAD

**Issue by elektito** [jrialland/python-astar#28]
I was under the impression that the implementation of `heuristic_cost_estimate` should only affect performance, not results. But in this case, I'm seeing one implementation causes the result to be wrong:

```python3
from astar import AStar

M = 8
n = 15
A = [1, 4, 3, 6, 7, 1, 2, 2, 5, 2, 3, 3, 2, 1, 7]
B = [3, 7, 2, 1, 1, 8, 6, 5, 5, 4, 1, 2, 4, 8, 2]

class MyAstar(AStar):
    def neighbors(self, node):
        return [i for i in range(1, n+1) if i != node]

    def distance_between(self, n1, n2):
        return (A[n1-1] + B[n2-1]) % M

    def heuristic_cost_estimate(self, current, goal):
        return goal - current
        #return self.distance_between(current, goal)

    def is_goal_reached(self, current, goal):
        return current == goal

a = MyAstar()
print(list(a.astar(1, 15)))
```

This would print [1, 15] which has a cost of 3. If I use the actual implementation of `distance_between` for `heuristic_cost_estimate` (the commented line), I get [1, 4, 15] which with a cost of 2 is the correct result.

**Comment by jrialland** [comment]
Your implementation of distance_between is wrong, (should most probably be a substraction, not an addition)
